### ISSUE TITLE
OpenNOP issue, Both Router do Optimization but No Deoptimization

### ISSUE THREAD

**Issue by mania25** [OpenNOP/opennop#23]
Hi,

I have an issue with OpenNOP, i've already configured OpenNOP using Inline deployment, which my OpenNOP server act as gateway for my LAN Network, and the issue i had was the OpenNOP server only do optimization, and no one do deoptimization, i didn;t know if i was misconfigured the opennop or not, need your help please

Thank you

NB: I'm using topology inline deployment, and also using fedora 21 64 bit on OpenNOP Router, and got OpenNOP build from source

OpenNOP Router 1 Init State:

![](https://sourceforge.net/p/opennop/support-requests/7/attachment/OpenNOP%20Router%201%20Initialize%20State.PNG)

OpenNOP Router 2 Init State:

![](https://sourceforge.net/p/opennop/support-requests/7/attachment/OpenNOP%20Router%202%20Initialize%20State.PNG)

Client Fetch Data From Web Server:

![](https://sourceforge.net/p/opennop/support-requests/7/attachment/Client%20Fetch%20Data%20From%20WebServer.PNG)

OpenNOP Router 1 State When Client Downloading Data: 

![](https://sourceforge.net/p/opennop/support-requests/7/attachment/OpenNOP%20Router%201%20State%20When%20Client%20Downloading%20Data%20From%20Web%20Server.PNG)

OpenNOP Router 2 State When Client Downloading Data: 

![](https://sourceforge.net/p/opennop/support-requests/7/attachment/OpenNOP%20Router%202%20State%20When%20Client%20Downloading%20Data%20From%20Web%20Server.PNG)

Inline Deployment Topology

![](https://sourceforge.net/p/opennop/support-requests/7/attachment/Topology.PNG)

**Comment by yaplej** [comment]
Because your router is in the same subnet as the destination VMs that traffic will be delivered directly to the destination without ever going through the 2nd OpenNOP server to be de-optimized.

You need to change your topology just a little so traffic will flow through both OpenNOP nodes.
1. Use a different network/subnet between the routers and OpenNOP nodes
2. Use an out-of-line topology
3. Use the OpenNOP nodes as your routers

**Comment by yaplej** [comment]
Also your sessions show Optimizing = No.  So its not actually doing any optimization because it does not detect the 2nd OpenNOP node in the traffic flow.

**Comment by mania25** [comment]
which network has same subnet?the destination vm is 172.128.2.2 the router is 10.11.227.1, is it in the same subnet?

**Comment by yaplej** [comment]
Router1 and OpenNOP1 are in the same subnet also Router2 and OpenNOP2 are in the same subnet.

When traffic is flowing back to be de-optimized its not going to traverse through the 2nd OpenNOP node.  The router will deliver it directly to the client instead of to the OpenNOP node for de-optimization.

**Comment by mania25** [comment]
you mean OpenNOP outgoing interface is on same network as Incoming interface the router? okay i've tried to change it, thank you for you information, i will inform if it work or not

**Comment by mania25** [comment]
okay, everything works now, i was forgot that i was add NAT rule on the router 1, that's why the IP Client on OpenNOP 2 changed, after i removed that rule and re-adding neighbor ip, everything works like a charm, thank you for your support, i think i will write some tutorial about this because it was really hard for me to understand the concept of this platform,
